### ISSUE TITLE
qaac Quality option 

### ISSUE THREAD

**Issue by neptune84x** [nu774/qaac#107]
Hello,
On the macOS side, the AAC encoder has an option like q3 (Quality 127), which is different from q2 High (Quality 96). In the Apple Compressor app, the AAC encoder is applied when Maximum quality is selected. I wonder if this is possible for qaac.

**Comment by nu774** [comment]
Hi,
You can already use -q 3, in which case qaac actually requests 127 to the AudioConverter.
However, that results in quality 96 in Windows CoreAudio toolbox.

Implementation details goes like this:

(opts.quality + 1) * 32 is passed to the AudioCoverterXX.
If you pass -q 3, computed value will be 128:
https://github.com/nu774/qaac/blob/master/main.cpp#L243

quality is cropped so that it doesn't go above 127(kAudioConverterQuality_Max)
So, 128 becomes 127:
https://github.com/nu774/qaac/blob/master/AudioConverterXX.cpp#L100

finally, it is passed to the AudioConveter:
https://github.com/nu774/qaac/blob/master/AudioConverterX.cpp#L240

**Comment by neptune84x** [comment]
Thank you for your valuable reply. As far as I understand, the “Quality 96” thing we already see on the Windows terminal is the same as the Maximum quality of Apple Compressor.

**Comment by neptune84x** [comment]
Hello, you probably gave the answer at the top, but I'm asking to make sure. I am using StaxRip. If Qaac -q is not specified, is it set to 2 or 3 by default? Or is Max Quality already -q 2 set by default? Thank you.

**Comment by nu774** [comment]
Default is 2 by default.
