### ISSUE TITLE
clipping after --limiter

### ISSUE THREAD

**Issue by svpv** [nu774/qaac#31]
Hello,
I noticed that, even when using --limiter, some of the encoded material clips.

$ sox -n -e float -b 32 -t wav - synth 5 sin 2000 >out.wav
$ ./maxsample out.wav
1.000000           

So this is a sine wave with max amplitude which I now try to encode.

$ qaac out.wav -o out.m4a && qaac --decode out.m4a -o dec.wav && ./maxsample dec.wav
...
1.041306

So the decoded content clips by quite an amount.
Adding --limiter to the encoder does not help:

$ qaac --limiter out.wav -o out.m4a && qaac --decode out.m4a -o dec.wav && ./maxsample dec.wav
...
1.048307

And it gets worse when adding --gain:

$ qaac --gain 10 --limiter out.wav -o out.m4a && qaac --decode out.m4a -o dec.wav && ./maxsample dec.wav
1.119114

$ cat maxsample.c
#include &lt;stdio.h&gt;
#include &lt;sndfile.h&gt;

double maxsample(const char *f)
{
        SF_INFO sfinfo;
        SNDFILE *sf = sf_open(f, SFM_READ, &sfinfo);
        double max = 0;
        sf_command(sf, SFC_CALC_MAX_ALL_CHANNELS, &max, sizeof max);
        return max;
}

int main(int argc, char *argv[])
{
        printf("%f\n", maxsample(argv[1]));
        return 0;
}

**Comment by nu774** [comment]
> $ qaac out.wav -o out.m4a && qaac --decode out.m4a -o dec.wav && ./maxsample dec.wav
> ...
> 1.041306
>
> So the decoded content clips by quite an amount.

NO. It isn't clipped. Peak beyond 0dBFS doesn't mean it's clipped.
Clipping occurs when converting floating point signals to integer. Since integer sample cannot represent value beyond 0dBFS, any sample beyond 0dBFS has to be *clipped* to 0dBFS.  This way signal is modified in nonlinear manner, yielding distortions sometimes audible. This *IS* the clipping. Even an AAC file has peak beyond 0dBFS, as long as you are using floating point decoder / processing chain, and you reduce the gain before sending signals to DAC, you are completely free from clipping.

Having said that... Yes, the encoded result will easily go beyond 0dBFS.
--limiter just work on input source (PCM) level, and it guarantees nothing on the encoded result. Typically, lossy encoding changes peak level (sometimes drastically), and you cannot predict peak of the outcome beforehand.

> And it gets worse when adding --gain:
> 
> $ qaac --gain 10 --limiter out.wav -o out.m4a && qaac --decode out.m4a -o dec.wav && ./maxsample dec.wav
> 1.119114

This is quite natural. After "--gain 10", the signal gets 10dB louder. Why do you think it should be better after that?
