### ISSUE TITLE
AAC-HE Mode Will Not Encode To Mono From Mono Source

### ISSUE THREAD

**Issue by czchmate** [nu774/qaac#38]
I am not sure if it is an integrated part of the specification or not, but I wanted to let you know that the AAC-HE encode mode does not create a mono file when using a mono 16-bit WAV source. Tested QAAC version was compiled from today's master source code.

I did not try manually specifying the channel numbers in the QAAC command line.

Cheers!

**Comment by nu774** [comment]
No, try investigating the resulting HE-AAC file with MediaInfo. It Is actually a mono HE-AAC and MediaInfo can show it.
However, many decoders just decode mono HE-AAC into stereo because they cannot distinguish mono HE-AAC from HE-AACv2 (stereo) file until whole frame is processed to see if PS extension is present (this is not specific to files encoded by qaac).

**Comment by czchmate** [comment]
Right on. Sorry about that.

Audacity was loading a Stereo file/project instead of Mono and it typically doesn't do that unless it is actually a Stereo file. I'll let them know.

**Comment by ValZapod** [comment]
This is indead working as intending, but we in ffmpeg now warn if this happens in -v debug level:

https://github.com/FFmpeg/FFmpeg/commit/6406d5e430953085a0100b44dd8fceb478b383e2

The aac_fixed decoder was also fixed.

> stereo because they cannot distinguish mono HE-AAC from HE-AACv2 (stereo)

Or even in some cases HE-AAC can have samples that make it stereo after 100 samples in!! CAn you imagine? See: http://fate-suite.ffmpeg.org/aac/al_sbr_ps_06_new.mp4
