### ISSUE TITLE
Provide a more universal example in the wiki

### ISSUE THREAD

**Issue by vilyaair** [nu774/qaac#48]
Concerning [Encoding from pipeline](https://github.com/nu774/qaac/wiki/Examples#encoding-from-pipeline), I believe that it is more versatile to use ffmpeg instead of flac:
`ffmpeg -i foo.tak -f wav -c pcm_s32le -v 0 - | qaac -V 100 --ignorelength - -o foo.m4a` 

The option "-c pcm_s32le" is added because ffmpeg always uses pcm_s16le codec when converting to wav format, regardless of the original audio bit depth.

Given that foo.tak is a audio file with 24 bit depth,
`takc -d foo.tak - | qaac -V 100 --ignorelength - -o tak.m4a` 
`ffmpeg -i foo.tak -f wav -c pcm_s24le -v 0 - | qaac -V 100 --ignorelength - -o ffmpeg24.m4a` 
`ffmpeg -i foo.tak -f wav -c pcm_s32le -v 0 - | qaac -V 100 --ignorelength - -o ffmpeg32.m4a` 

The above codes yield the bit-exact same track, verified by Binary Comparator component of foobar2000. In addition, the output file will have no difference if the output format is ADTS or CAF.

**Comment by nu774** [comment]
Well, it's true that ffmpeg is versatile, but the purpose of the example is to explain how to use qaac command line, and what only matters here is that you can use "-" as a input filename to pipe audio to qaac.
The example using ffmpeg gets longer due to more necessary options which has nothing to do with qaac's usage, and this is not the place to tell you how to use ffmpeg.

**Comment by vilyaair** [comment]
I am conscious of the purpose of examples. Sorry for my silly request.
