### ISSUE TITLE
Tag support for WAV files

### ISSUE THREAD

**Issue by xerces8** [nu774/qaac#49]
Currently (v2.64), when converting WAV files to AAC, like this: qaac64 example.wav

The tags/metadata in the WAV file are lost/ignored.

Can you please add support for them?

**Comment by nu774** [comment]
WAV files can have multiple tagging scheme (INFO, BWF, XMP, MP3 ...).
INFO is the most standard one, but it supports only limited sets of tags, and character encoding is UNDEFINED. It can be UTF-8 or locale specific encoding. There's no way for us to know which encoding being used, since there's no encoding declaration in the file.
Windows media player and iTunes don't support WAV tags for good reason. Will qaac support it? NO. I'm not interested in it.

**Comment by xerces8** [comment]
I respect your choice, but a correction: WMP does support WAV tags, so does
foobar2000, VLC, and the Windows File Explorer (the file properties dialog
shows the tag values). Those are that I tested quickly, there are probably
many others.

**Comment by nu774** [comment]
> Those are that I tested quickly
Yeah, it seems that you looked at them only "quickly".

In WMP it looks like you can edit titles or something of WAV files but they are not saved in the WAV file. Just look at the resulting file in Windows explorer property or fb2k or something.
As for fb2k, it writes tags in INFO and ID3 tags but supports only ASCII for INFO.
Try setting some non-ascii characters in fb2k metadata editor, and look at the resulting file in Windows explorer (which look for only INFO tags).

The situation is shit, and I have no reason to support this shit.
