### ISSUE TITLE
Missing Artist tag in m4a when cue sheet (with flac) with --concat is used as input

### ISSUE THREAD

**Issue by chros73** [nu774/qaac#50]
First of all thanks for this great util!

Creating transcoded single tracks from cue file (+flac) is working great with `--fname-format` switch and [${artist}](https://github.com/nu774/qaac/wiki/Customizing-file-name-generation) variable.

I wanted to create just one file (mix) from cue file with `--concat` switch and I noticed that Artist tag is missing from the resulted track info:
- checked with [Aimp](http://www.aimp.ru/)
- and [mp3tag](https://www.mp3tag.de/en/)

Although when I edited the missing Artist tags with mp3tag, Aimp still didn't recognise them (so it can be an Aimp bug).

**Comment by nu774** [comment]
Only "shared" tags whose value matches between all the input files are kept, except for the "title" tag.
"title" tags are specially stored as chapter titles in the concatenated output.
All the other per-track tags are lost, since there's no way to store them.

In short, there's no way for you to concatenate multiple artist files keeping the artist tags.
This is the limitation of MP4 chapter format. It's not versatile enough to store multiple metadata in chapters.

**Comment by chros73** [comment]
> This is the limitation of MP4 chapter format

Thanks, I didn't know this either. That means mp3tag does something strange.
So it doesn't make any sense to use this with VA mixes. I'll go with the traditional m4a + cue way then.

Probably it'd be good to add this info onto the `--concat` cue sheet part of  [About input format](https://github.com/nu774/qaac/wiki/About-input-format#handling-of-multiple-input-or-cuesheet)  page.
