### ISSUE TITLE
QAAC generates undeletable folder in Windows with "/" in outfile name

### ISSUE THREAD

**Issue by iAvoe** [nu774/qaac#78]
Encountered a repeatable issue on my system.

**Command used:**
[qaac64.exe --cvbr 320 -b 16 -r 44100 --threading -o "D:\Desktop\xxx / xxx.aac" "D:\Desktop\\*.wav"]

**Symptom:**
Generates "D:\Desktop\xxx\xxx.aac", the xxx folder is 0Byte in size even though xxx.aac is in folder and file is all normal, the "xxx" folder is dead locked to the output directory and survives reboot

Failed attempts:
CMD running [del], [rmdir], with & without [\\\\?\\] failes to delete, returns "File could not be found"

**Temp solution:**
I've painfully spent an hour, finally got that thing deleted by 3rd party hard drive management software (I used Partition-guru); (and then I forgot to alter command and generated another folder...)

**Windows specs:**
Ver 1809, build 17763.2746

**Hardware specs:**
x470 Aorus Ultra gaming BIOS F63a
r7 5800x
2×8GB memory
All drives are running under GPT partition

**Comment by nu774** [comment]
qaac generated such a directory because you exactly told it to do so.
If you had difficulty in removing it, it's Windows issue.

https://superuser.com/questions/565334/rename-delete-windows-x64-folder-with-leading-and-trailing-space
https://answers.microsoft.com/en-us/windows/forum/all/remove-a-folder-with-space-at-the-end/2db209ad-9e82-41dd-b05b-4ed681845aa9

**Comment by iAvoe** [comment]
Thanks for reply, didn't realize it was the blank space causing this issue. I would say add a warning text just in case other people stumble upon this. I'll close this issue
