### ISSUE TITLE
qaac creates a noise when the input is a simple wav but not when it's piped through ffmpeg

### ISSUE THREAD

**Issue by pcroland** [nu774/qaac#83]
![img](https://envs.sh/QdS.png)
A friend of mine told me that qaac creates a noise at the end of the track when it's not piped through ffmpeg. It's weird because we use the same `CoreAudioToolbox.dll` and same qaac. It seems that the only difference is that he's using Windows 11 while I use Windows 10.

**Comment by nu774** [comment]
I'm also using Windows 11 but I haven't seen this.
If it's ok when fed from ffmpeg, it's likely happening on the input side. What is the format of input? Do you use the same DLLs? (for example, libFLAC, libwavpack, libsndfile)

**Comment by pcroland** [comment]
Input is a wav created with `ffmpeg -i in -c:a pcm_s16le out`.

**Comment by nu774** [comment]
`ffmpeg -i in -c:a pcm_s16le -f wav out.wav`
right?
The issue doesn't reproduce here.

**Comment by pcroland** [comment]
Yes. I have couple of friends who use qaac but this problem only occurs for two of them. I also can't reproduce it. Any ideas what tests we should do?

**Comment by nu774** [comment]
Maybe you could try some options.
- qaac 32bit/64bit
- AAC/ALAC(-A)/WAV(-D) output
- different PCM container other than WAV (AIFF or CAF)

**Comment by pcroland** [comment]
Turned out it was Audition's messed up wav exporter.

**Comment by pcroland** [comment]
Here's an audition exported sample which will produce the weird end: [shitty audition wav](https://envs.sh/Qdr.wav)

**Comment by nu774** [comment]
Although this file contains metadata at the end of the file, data chunk size is properly set. qaac will normally treat only data chunk as PCM. 
Probably your friends were using -i (--ignorelength) option.

**Comment by pcroland** [comment]
Yeah, we both use it. What's the reason that it doesn't happen with ffmpeg created files?

**Comment by nu774** [comment]
RIFF/WAV file format is not a simple header + payload(audio) format.
It's a chunked format. It consists of multiple sub chunks (chunk id + payload size + payload).
Audio PCM data is contained as a payload of "data" chunk. So, it's length (in bytes) is declared as the payload size of the data chunk.
Usually, data chunk is at the end of a WAV file. But as you've seen in this example, it's not always the case.
Therefore, in order not to read beyond the end of the data chunk, you have to obey WAV file structure.

However, in some cases payload size declared in the file is not correct, and you need to ignore it. `--ignorelength` exists for that purpose. It tells qaac to forcibly ignore the payload size declared  
 in the WAV file. When this option is set, qaac assumes that audio data is filled until the end of the WAV file (since there's no way to know the  boundary).

If you pipe in WAV format, the feeder side usually cannot write correct payload size beforehand (since it is unknown until all data are written). Therefore, feeder application usually put some placeholder value there (it's zero in case of ffmpeg). This implies that pipe feeder can write nothing after audio data.
